name: 'Check PR Title'

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches-ignore:
      - 'changeset-release/main'

jobs:
  check_pr_title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const prTitle = context.payload.pull_request.title;

            const pattern = /^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)\((JIRA-\d+)\):\s.+/;

            if (!pattern.test(prTitle)) {
              core.setFailed(
                `PR title does not match the standard.\n` +
                `Please use the 'type(JIRA-XXX): description' format.\n\n` +
                `Example: 'feat(JIRA-123): Add new feature'\n` +
                `Example: 'fix(JIRA-456): Fix bug'`
              );
            } else {
              core.info('PR title is valid.');
            }
