name: "Check Branch Name"

on:
  push:
    branches-ignore:
      - "main"

jobs:
  check_branch_name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const branchName = context.ref.replace("refs/heads/", "");
            const pattern = /^(JIRA-\d+)$/;

            if (!pattern.test(branchName)) {
              core.setFailed(
                `Branch name (${branchName}) does not match the standard.\n` +
                `Please use the 'JIRA-XXX' format.`
              );
            } else {
              core.info("Branch name is valid.");
            }
